Master:
  Name: jenkins-m
  Image: "builditdigital/jenkins-master"
  ImageTag: "latest"
  Component: "jenkins-m"
  UseSecurity: false
  ServiceType: ClusterIP
  HostName: "jenkins-m.kube.local"

Persistence:
  Enabled: true
  StorageClass: generic
  AccessMode: ReadWriteOnce
  Size: 4Gi

Agent:
  Image: jenkinsci/alpine
  ImageTag: 2.52
