Master:
  Image: "builditdigital/jenkins-master"
  ImageTag: "latest"
  UseSecurity: false
  ServiceType: ClusterIP
  HostName: "jenkins-m.kube.local"

Persistence:
  Enabled: true
  StorageClass: generic
  AccessMode: ReadWriteOnce
  Size: 4Gi

Agent:
  Image: jenkinsci/jnlp-slave
  ImageTag: alpine
