== What is it?

Dockerized version of Jenkins-based CD pipeline.

== EC2 Deployment

1. create CentOS7 machine with 8+ GB RAM and 10G+ EBS (I used existing VPC)
1. install docker (https://docs.docker.com/engine/installation/linux/centos/) and docker-compose
1. open docker api tcp socket (change daemon parameters to include `-H tcp://0.0.0.0:2376`)
1. add corresponding wildcard Route53 record pointing to this machine (I used *.docker.riglet)

== Local (MacOS) Deployment

1. install docker for mac and docker-compose
1. open docker api tcp socket on corresponding vbox interface (i used `socat TCP-LISTEN:2376,range=0.0.0.0/0,reuseaddr,fork UNIX:/var/run/docker.sock`)

== Start
1. clone this repo
1. build `rig/jenkins`, `rig/slave`, `rig/node_slave` images
1. fire up docker-compose

== Configure Jenkins

1. disable global security or change admin password
1. set global vars (`DOCKER_HOST=tcp://yourhost:2376` and `DOCKER_SERVER=yourhost`) to match exposed tcp socket on the host
1. add docker cloud provider (use `DOCKER_HOST` as URL)
1. add template for node/jenkins (`rig/node_slave` image + privileged flag)

== Example job to build-test-deploy web application
[source,groovy]
----
node('docker-node') {
    stage('Checkout') {
        git(url: 'https://github.com/buildit/digitalrig-acceptance-tests.git')
    }
    stage('Build') {
        dir('./src/test/apps/node-docker') {
            sh 'npm install && npm run dist'
            def sampleContainer = docker.build 'my-environment:snapshot'
            sampleContainer.withRun('-p 18080:80') {
                sh "URL=http://$DOCKER_SERVER:18080# xvfb-run --server-args='-screen 0, 1024x768x16'  npm run test:e2e"
            }
        }
    }
    stage('Deploy') {
        try {
            sh 'docker stop test'
            sh 'docker rm test'
        } catch(Exception e) {
            // nothing
        }
        sh 'docker run --name test --network digitalrigdocker_default -d  my-environment:snapshot'
    }
}
----