apiVersion: v1
kind: Secret
metadata:
  name: openvpn
data:
  dh.pem: <<base64>>
  certs.p12: <<base64>>
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: openvpn
  labels:
    name: openvpn
spec:
  replicas: 1
  selector:
    name: openvpn
  template:
    metadata:
      labels:
        name: openvpn
    spec:
      containers:
        - name: openvpn
          image: offlinehacker/openvpn-k8s
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: OVPN_NETWORK
              value: 10.240.0.0
            - name: OVPN_SUBNET
              value: 255.255.0.0
            - name: OVPN_PROTO
              value: tcp
            - name: OVPN_K8S_SERVICE_NETWORK
              value: 172.20.0.0
            - name: OVPN_K8S_SERVICE_SUBNET
              value: 255.255.0.0
            # USE K8S DNS!
            # TODO: should be populated automatically from cluster setup
            - name: OVPN_K8S_DNS
              value: 100.64.0.10
            - name: OVPN_K8S_DOMAIN
              value: svc.cluster.local
            - name: OVPN_K8S_POD_NETWORK
              value: 100.0.0.0
            - name: OVPN_K8S_POD_SUBNET
              value: 255.0.0.0
          ports:
            - name: openvpn
              containerPort: 1194
          volumeMounts:
            - mountPath: /etc/openvpn/pki
              name: openvpn
      volumes:
        - name: openvpn
          secret:
            secretName: openvpn
---
kind: Service
apiVersion: v1
metadata:
  name: openvpn
spec:
  ports:
    - name: openvpn
      port: 1194
      targetPort: 1194
  selector:
    name: openvpn
  type: LoadBalancer