apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: kube-system
  labels:
    k8s-app: kibana-logging
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5601
  selector:
    k8s-app: kibana-logging
