Master:
  Image: "builditdigital/jenkins-master"
  ImageTag: "latest"
  UseSecurity: false
  ServiceType: ClusterIP
  HostName: "jenkins.riglet"
  InitScripts:
  - |
    import jenkins.plugins.git.GitSCMSource
    import org.jenkinsci.plugins.workflow.libs.GlobalLibraries
    import org.jenkinsci.plugins.workflow.libs.LibraryConfiguration
    import org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever

    def buildit = new LibraryConfiguration("buildit",
                              new SCMSourceRetriever(
                                      new GitSCMSource(
                                              "git", "https://github.com/buildit/jenkins-pipeline-libraries.git",
                                              null, "*", null, true)))
    buildit.defaultVersion = 'master'
    GlobalLibraries.get().setLibraries([buildit])

Persistence:
  Enabled: true
  StorageClass: generic
  AccessMode: ReadWriteOnce
  Size: 8Gi

Agent:
  Image: jenkinsci/jnlp-slave
  ImageTag: alpine
