nginx:
  replicaCount: 1
  image:
    repository: builditdigital/nginx-ingress-controller
    tag: "0.9.0-beta.2-1"
    pullPolicy: IfNotPresent
  monitoring: true
  watchNamespace: public
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  configmap:
    proxy_connect_timeout: "30"
    proxy_read_timeout: "600"
    proxy_send_imeout: "600"
    hsts_include_subdomains: "false"
    body_size: "32m"
    server_name_hash_bucket_size: "256"
    enable_vts_status: "true"
default:
  replicaCount: 1
  image:
    repository: gcr.io/google_containers/defaultbackend
    tag: "1.0"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 0.1
      memory: 64Mi
    requests:
      cpu: 0.1
      memory: 32Mi
