= Helm-based rig deployment on kubernetes cluster

== Prerequisites

* https://github.com/kubernetes/helm[Helm] 2.x
* Kubernetes / Minikube 1.5.x

== Minikube-specific steps

If you want to have access to dynamically provisioned persistent volumes:
. Create host directory comewhere below /Users (for macos)
. Set permissions on this dir to allow Minikube create content in it (should it use user creds?)
. Replace path in Minikube VM `sudo rm -r /tmp/hostpath_pv && sudo ln -sf /Users/you/path/to/pv /tmp/hostpath_pv`

== Installation

. Clone https://github.com/electroma/charts/[fork][fork] of `kubernetes/charts` to the directory on the same level
. Configure files under `vars/`
. Execute `rig_install.sh` or `ec2_rig_install.sh` (make sure you're using correct cluster)
. If you're running on minikube and want to VPN into POD netowk - you may need to make sure network is configured correctly
.. `minikube ssh` and check `sudo udhcp` - it should give you the understanding of b2d dns setup
.. Make sure corresponding route is in place
.. In case you want to make changes to DNS configuration most likely you gonna need to restart kube-dns
----
kubectl delete pod -n kube-system `kubectl get pods -n kube-system -l "k8s-app=kube-dns" --template "{{ range .items }}{{.metadata.name}} {{end}}"`
----
. In case you're running Minikube and wand your PVCs be really persistent add `ln -s /Users/{{ .Some.Existing.Path }} /tmp/hostpath_pv` to `/opt/bootlocal.sh` (may changes after https://github.com/kubernetes/minikube/pull/690[PR#690])

== Making changes in charts

We're using https://github.com/electroma/charts/[fork] of https://github.com/kubernetes/charts[kubernetes/charts].

In case you need to make change in an existing chart or create new public chart:

. Create feature branch from `baseline` branch
. Make and test your changes
. Create PR to upstream (there are some https://github.com/electroma/charts/blob/master/CONTRIBUTING.md[rules])
. Merge your chages to `master` branch to make it available
. Once your PR is merged
.. Sync `upstream` branch from `kubernetes/charts`
.. Merge `upstream` to `master`
