Master:
  Image: "builditdigital/jenkins-master"
  ImageTag: "latest"
  UseSecurity: false
  ServiceType: ClusterIP
  HostName: "jenkins.riglet"

Persistence:
  Enabled: true
  StorageClass: generic
  AccessMode: ReadWriteOnce
  Size: 8Gi

Agent:
  Image: jenkinsci/jnlp-slave
  ImageTag: alpine
